[project]
name = "app_fastapi"
version = "0.1.0"
requires-python = ">={{ cookiecutter.minimum_python_version }}"
description = "A FastAPI app for {{ cookiecutter.project_name }}"
authors = [{ name = "{{ cookiecutter.author_name }}" }]
dependencies = [
    "fastapi", 
    "uvicorn", 
    "pydantic", 
    "python-dotenv"
]

[tool.uv.sources]
src = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/app_fastapi"]
