repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.5
  hooks:
    # Run the linter with auto-fix enabled
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter
    - id: ruff-format
      types_or: [ python, pyi ]
- repo: https://github.com/kynan/nbstripout
  rev: 0.5.0
  hooks:
    - id: nbstripout