[project]
name = "{{ cookiecutter.package_name }}"
version = "0.0.1"
description = "{{ cookiecutter.description }}"
authors = [{ name = "{{ cookiecutter.author_name }}" }]
requires-python = ">={{ cookiecutter.minimum_python_version }}"
dependencies = [
  # Packages
  "app_fastapi",
  "app_streamlit",
  "azureml",

  # Global dependencies
  "PyYAML",

  # Conditional dependencies
  {% if cookiecutter.database_type == 'postgres' -%}
  "psycopg2-binary",
  {% elif cookiecutter.database_type == 'mysql' -%}
  "mysql-connector-python",
  {% endif -%}
]

[dependency-groups]
dev = [
  "coverage",
  "pytest",
  "ruff",
  "pre-commit",
]

[tool.nbstripout]

[tool.uv.sources]   
# Search for these dependencies as workspaces rather than in PyPI    
app_fastapi = { workspace = true }
app_streamlit = { workspace = true }
azureml = { workspace = true }

[tool.uv.workspace]
members = [
  # Define packages as member of the workspace
  "app_fastapi",
  "app_streamlit",
  "azureml"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/{{ cookiecutter.package_name }}"]
