[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{{ cookiecutter.package_name }}"
version = "0.0.1"
description = "{{ cookiecutter.description }}"
authors = [
  { name = "{{ cookiecutter.author_name }}" }
]
dependencies = [
  "PyYAML",
  "python-dotenv",
  {% if cookiecutter.azure_ml_project|lower in ['y', 'yes'] -%}
  "azure-ai-ml",
  "azure-identity",
  {% endif -%}
  {% if cookiecutter.database_type == 'postgres' -%}
  "psycopg2-binary",
  {% elif cookiecutter.database_type == 'mysql' -%}
  "mysql-connector-python",
  {% endif -%}
]

[project.optional-dependencies]
dev = [
  "ruff",
  "coverage",
  "pyproject-flake8",
  "pre-commit",
  "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.nbstripout]